import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        resizeMode: 'cover',
        justifyContent: 'center',   
        alignItems: 'center',   
    },
    title: {
        fontSize: 35,
        color: 'black',
        fontWeight: 600,
        textAlign: 'center',
        marginTop: 30,
        marginBottom: 30,
    },
    quantityContainer: {
        width: 330,
        height: 320,
        borderWidth: 1,
        borderColor: 'black',
        backgroundColor: '#F5F5F7',
        borderRadius: 30,
        display: 'flex',
        alignContent: 'center',
        justifyContent: 'center',
        boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.50)',
    },
    quantityText: {
        fontSize: 40,
        fontWeight: 600,
        color: 'black',
        textAlign: 'center',
    },
    quantityBtn: {
        width: '68%',
        height: 130,
        marginBottom: 15,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        alignSelf: 'center',
    },
    addBtn: {
        width: 75,
        height: 70,
        backgroundColor: '#F5F5DC',
        borderRadius: 10,
        borderWidth: 1,
        boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.25)',
        alignContent: 'center',
        justifyContent: 'center',
    },
    deducBtn: {
        width: 75,
        height: 70,
        backgroundColor: '#F5F5DC',
        borderRadius: 10,
        borderWidth: 1,
        boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.25)',
        alignContent: 'center',
        justifyContent: 'center',
    },
    addBtnText: {
        fontSize: 45,
        color: 'black',
        textAlign: 'center',
    },
    deducBtnText: {
        fontSize: 45,
        color: 'black',
        textAlign: 'center',
    },
    logoutBtn: {
        width: 150,
        height: 65,
        marginTop: 50,
        borderRadius: 30,
        borderWidth: 1,
        borderColor: 'black',
        backgroundColor: 'white',
        alignContent: 'fled-end',
        justifyContent: 'center',
    },
    logoutBtnTxt: {
        fontSize: 18,
        color: 'black',
        textAlign: 'center',
        fontWeight: 600,
    }
})

export default styles;